#!/usr/bin/env npx tsx
/**
 * Setup script for example apps.
 *
 * Discovers party IDs from cn-quickstart using Keycloak OAuth2,
 * and writes .env files for each example app.
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const PARTICIPANT_USER_URL = "http://localhost:2975";
const PARTICIPANT_PROVIDER_URL = "http://localhost:3975";

// Keycloak OAuth2 credentials (from cn-quickstart)
const PAYER_TOKEN_URL =
  "http://keycloak.localhost:8082/realms/AppUser/protocol/openid-connect/token";
const PAYER_CLIENT_ID = "app-user-validator";
const PAYER_CLIENT_SECRET = "6m12QyyGl81d9nABWQXMycZdXho6ejEX";

const PAYEE_TOKEN_URL =
  "http://keycloak.localhost:8082/realms/AppProvider/protocol/openid-connect/token";
const PAYEE_CLIENT_ID = "app-provider-validator";
const PAYEE_CLIENT_SECRET = "AL8648b9SfdTFImq7FV56Vd0KHifHBuC";

const AUDIENCE = "https://canton.network.global";

async function fetchOAuth2Token(
  tokenUrl: string,
  clientId: string,
  clientSecret: string,
): Promise<string> {
  const body = new URLSearchParams({
    grant_type: "client_credentials",
    client_id: clientId,
    client_secret: clientSecret,
    scope: "openid",
    audience: AUDIENCE,
  });

  const res = await fetch(tokenUrl, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString(),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(
      `OAuth2 token request failed at ${tokenUrl}: ${res.status} ${text}`,
    );
  }

  const data = (await res.json()) as { access_token: string };
  return data.access_token;
}

interface PartyDetail {
  party: string;
  isLocal: boolean;
}

async function discoverLocalParty(
  ledgerUrl: string,
  token: string,
  partyPrefix: string,
): Promise<string> {
  const res = await fetch(`${ledgerUrl}/v2/parties`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) {
    throw new Error(
      `Failed to discover parties at ${ledgerUrl}: ${res.status}`,
    );
  }
  const data = (await res.json()) as {
    partyDetails?: PartyDetail[];
  };
  const parties = data.partyDetails ?? [];
  // Find the local party matching the expected prefix (e.g. app_user, app_provider)
  const match = parties.find(
    (p) => p.isLocal && p.party.startsWith(partyPrefix),
  );
  if (match) return match.party;
  // Fallback: any local party that isn't a "participant::" party
  const localParty = parties.find(
    (p) => p.isLocal && !p.party.startsWith("participant::"),
  );
  return localParty?.party ?? "";
}

async function discoverDso(
  ledgerUrl: string,
  token: string,
): Promise<string> {
  // The DSO party is visible on participant nodes — find it from the party list
  try {
    const res = await fetch(`${ledgerUrl}/v2/parties`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (res.ok) {
      const data = (await res.json()) as { partyDetails?: PartyDetail[] };
      const dso = (data.partyDetails ?? []).find((p) =>
        p.party.startsWith("DSO::"),
      );
      if (dso) return dso.party;
    }
  } catch {}
  return "";
}

async function main() {
  console.log("Canton x402 SDK -- Example Setup\n");

  console.log("Fetching OAuth2 tokens from Keycloak...");
  const [payerToken, payeeToken] = await Promise.all([
    fetchOAuth2Token(PAYER_TOKEN_URL, PAYER_CLIENT_ID, PAYER_CLIENT_SECRET),
    fetchOAuth2Token(PAYEE_TOKEN_URL, PAYEE_CLIENT_ID, PAYEE_CLIENT_SECRET),
  ]);
  console.log("  Tokens acquired.\n");

  console.log("Discovering parties from cn-quickstart...\n");

  const [payerParty, payeeParty, dsoParty] = await Promise.all([
    discoverLocalParty(PARTICIPANT_USER_URL, payerToken, "app_user"),
    discoverLocalParty(PARTICIPANT_PROVIDER_URL, payeeToken, "app_provider"),
    discoverDso(PARTICIPANT_USER_URL, payerToken),
  ]);

  if (!payerParty || !payeeParty) {
    console.error("Could not discover parties. Is cn-quickstart running?");
    process.exit(1);
  }

  console.log(`  Payer (app-user):     ${payerParty}`);
  console.log(`  Payee (app-provider): ${payeeParty}`);
  console.log(`  DSO Party:            ${dsoParty || "(not found)"}`);
  console.log();

  const envContent = [
    `# Generated by setup.ts`,
    `PAYER_PARTY=${payerParty}`,
    `PAYEE_PARTY=${payeeParty}`,
    `CANTON_DSO_PARTY=${dsoParty}`,
    ``,
    `# OAuth2 credentials (Keycloak - cn-quickstart)`,
    `PAYER_TOKEN_URL=${PAYER_TOKEN_URL}`,
    `PAYER_CLIENT_ID=${PAYER_CLIENT_ID}`,
    `PAYER_CLIENT_SECRET=${PAYER_CLIENT_SECRET}`,
    `PAYEE_TOKEN_URL=${PAYEE_TOKEN_URL}`,
    `PAYEE_CLIENT_ID=${PAYEE_CLIENT_ID}`,
    `PAYEE_CLIENT_SECRET=${PAYEE_CLIENT_SECRET}`,
    ``,
    `# Canton participant URLs`,
    `CANTON_LEDGER_URL_USER=http://localhost:2975`,
    `CANTON_LEDGER_URL_PROVIDER=http://localhost:3975`,
    `CANTON_SCAN_PROXY_URL=http://scan.localhost:4000`,
    ``,
  ].join("\n");

  const exampleDirs = [
    "token-gated-docs",
    "cc-transfer-service",
    "balance-inquiry",
  ];

  for (const dir of exampleDirs) {
    const envPath = join(__dirname, "..", dir, ".env");
    writeFileSync(envPath, envContent);
    console.log(`  Wrote ${envPath}`);
  }

  console.log(
    "\nSetup complete! Make sure you have CC by tapping the faucet:",
  );
  console.log(
    "  Open http://wallet.localhost:2000 and tap CC for app-user\n",
  );
}

main().catch((err) => {
  console.error("Setup failed:", err);
  process.exit(1);
});
